apiVersion: v1
kind: Service
metadata:
    name: seaweedfs-headless
    namespace: database
spec:
    clusterIP: None
    selector:
        kubernetes.io/name: seaweedfs
    ports:
        - name: s3
          port: 8333
