apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-2
  namespace: production
  labels:
    app.kubernetes.io/name: nodejs-app-2
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http

    - port: 9464
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: nodejs-app-2
