apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: nodejs-app-2
  namespace: production
  labels:
    app.kubernetes.io/name: nodejs-app-2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nodejs-app-2
  podTargetLabels:
    - app.kubernetes.io/version
  namespaceSelector:
    matchNames:
      - production
  endpoints:
    - port: metrics
      path: /metrics
      interval: 20s
      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_version]
          targetLabel: version
          regex: (.+)
          replacement: $1
