apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path

  podSecurityContext:
    fsGroup: 26
    runAsUser: 26
    runAsGroup: 26
    fsGroupChangePolicy: OnRootMismatch

  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-db-user
